# Generated by Django 4.1 on 2022-08-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, help_text='seleccione una imagen para mostrar', null=True, upload_to='img/noticias'),
        ),
    ]
