# Generated by Django 4.1 on 2022-08-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='img',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_instagram',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_twitter',
        ),
    ]
