# Generated by Django 4.1 on 2022-08-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='evento', to='eventos_app.categoria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='img',
            field=models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/eventos'),
        ),
    ]
