# Generated by Django 4.1 on 2022-08-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='category',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='pubicado',
            new_name='publicado',
        ),
    ]
