# Generated by Django 4.1 on 2022-08-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_app', '0005_imagen_album_alter_imagen_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='álbumdefotos', to='recursos_app.albumfotos'),
        ),
    ]
