# Generated by Django 4.1 on 2022-08-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_app', '0006_alter_imagen_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, related_name='álbumdevideos', to='recursos_app.albumvideos'),
        ),
    ]
