# Generated by Django 4.1 on 2022-08-31 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_app', '0008_alter_imagen_categorias_alter_video_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='img',
            field=models.ImageField(help_text='seleccione una imagen', upload_to='img/recursos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(upload_to='videos/recursos', validators=[django.core.validators.FileExtensionValidator(['MOV', 'avi', 'mp4', 'webm', 'mkv'], 'No supported format')]),
        ),
    ]
